modLoader="javafml"
loaderVersion="[10,)"
license="Unlicense"

[[mods]]
modId="grandstrategy"
version="1.0.0"
displayName="Grand Strategy"
authors="AsbestosStar"
description='''
A grand strategy mod for Minecraft.
'''

[[mixins]]
config="grandstrategy.mixins.json"

[[dependencies.grandstrategy]]
    modId="neoforge"
    mandatory=true
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.grandstrategy]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1.2,)"
    ordering="NONE"
    side="BOTH"




