package com.asbestosstar.grandstrategy.common.engine;

import com.asbestosstar.grandstrategy.common.data.Civilisation;
import com.asbestosstar.grandstrategy.common.data.DataManager;
import com.asbestosstar.grandstrategy.common.data.FactoryRecipe;
import com.asbestosstar.grandstrategy.common.data.FactoryType;
import com.asbestosstar.grandstrategy.common.data.Ideology;
import com.asbestosstar.grandstrategy.common.data.MinecraftItemRegistry;
import com.asbestosstar.grandstrategy.common.data.Religion;
import com.asbestosstar.grandstrategy.common.data.Technology;
import com.asbestosstar.grandstrategy.common.data.VillagerJob;
import com.asbestosstar.grandstrategy.common.data.WorkerToolTier;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Server-authoritative data-driven research progression. */
public final class ResearchSystem {
    /**
     * Baseline research generated by an active civilisation every strategy second.
     * Technology baseResearchSeconds is calibrated against this rate, so a civilisation
     * with no dedicated researchers still completes an on-era technology in its stated
     * base time. Dedicated researchers accelerate that baseline instead of being a hard
     * requirement for research to move at all.
     */
    private static final double BASE_RESEARCH_POINTS_PER_SECOND = 0.03;
    private static final double RESEARCHER_SPEED_BONUS = 0.50;

    private ResearchSystem() { }

    public static void tick(long currentYear) {
        for (Civilisation civilisation : DataManager.getCivilisations().values()) {
            if (civilisation == null || !civilisation.isActive()) continue;
            grantBackwaterTechnologies(civilisation, currentYear);
            resolveSnapIdeology(civilisation, currentYear);
            tickActiveResearch(civilisation, currentYear);
        }
    }

    public static List<Technology> availableTechnologies(Civilisation civilisation, long currentYear) {
        if (civilisation == null) return List.of();
        return DataManager.getTechnologies().values().stream()
                .filter(ResearchSystem::technologyExistsInCurrentModSet)
                .filter(technology -> !civilisation.hasTechnology(technology.getId()))
                .filter(technology -> prerequisitesMet(civilisation, technology))
                .sorted(Comparator.comparingLong(Technology::getBaseYear)
                        .thenComparing(Technology::getName, Comparator.nullsLast(String::compareTo)))
                .toList();
    }

    public static boolean canStart(Civilisation civilisation, Technology technology) {
        return civilisation != null && technology != null
                && civilisation.isActive()
                && !civilisation.hasTechnology(technology.getId())
                && technologyExistsInCurrentModSet(technology)
                && prerequisitesMet(civilisation, technology);
    }

    public static boolean technologyExistsInCurrentModSet(Technology technology) {
        if (technology == null || technology.getId() == null) return false;
        for (String itemId : technology.getRequiredItemIds()) {
            if (!MinecraftItemRegistry.itemExists(itemId)) return false;
        }
        List<String> any = technology.getAnyRequiredItemIds();
        if (!any.isEmpty() && any.stream().noneMatch(MinecraftItemRegistry::itemExists)) return false;
        return true;
    }

    public static boolean prerequisitesMet(Civilisation civilisation, Technology technology) {
        if (civilisation == null || technology == null) return false;
        for (String prerequisite : technology.getPrerequisites()) {
            Technology prerequisiteTechnology = DataManager.getTechnologies().get(prerequisite);
            // Optional registry-backed technologies are allowed to sit directly in
            // the main progression. If their providing mod is absent, the prerequisite
            // itself does not exist in this mod set and is therefore bypassed. This is
            // what lets IRON -> STEEL -> DIAMOND collapse cleanly to IRON -> DIAMOND
            // on a vanilla-only installation.
            if (prerequisiteTechnology != null
                    && !technologyExistsInCurrentModSet(prerequisiteTechnology)) {
                continue;
            }
            if (!civilisation.hasTechnology(prerequisite)) return false;
        }
        return true;
    }

    public static double researchDurationModifier(Civilisation civilisation,
                                                   Technology technology,
                                                   long currentYear) {
        if (civilisation == null || technology == null) return 1.0;
        long delta = technology.getBaseYear() - currentYear;
        double eraModifier;
        if (delta > 0) {
            // Hundreds of years ahead becomes meaningfully expensive; thousands
            // ahead is possible but intentionally very slow rather than forbidden.
            eraModifier = 1.0 + Math.min(24.0,
                    0.42 * Math.pow(delta / 100.0, 1.22));
        } else {
            long behind = -delta;
            eraModifier = Math.max(0.12, 1.0 / (1.0 + behind / 450.0));
        }

        double religionModifier = 1.0;
        double religiousShare = civilisation.getReligiousPopulationShare();
        double extremism = civilisation.getReligiousExtremism() / 100.0;
        religionModifier += religiousShare * (0.20 + 0.70 * extremism);
        if (!"secular".equalsIgnoreCase(civilisation.getStateReligionId())) {
            religionModifier += 0.15 + 0.35 * extremism;
        }
        Religion stateReligion = DataManager.findReligion(civilisation.getStateReligionId());
        if (stateReligion != null) {
            religionModifier *= Math.max(0.50, 1.0 - stateReligion.getResearchModifier());
        }

        double ideologyModifier = 1.0;
        Ideology ideology = DataManager.findIdeology(civilisation.getIdeology());
        if (ideology != null) {
            double research = ideology.getModifiers().getOrDefault("research", 0.0);
            ideologyModifier = Math.max(0.50, 1.0 - research);
        }

        return Math.max(0.08, Math.min(40.0, eraModifier * religionModifier * ideologyModifier));
    }

    public static double requiredResearchPoints(Civilisation civilisation,
                                                Technology technology,
                                                long currentYear) {
        return technology.getBaseResearchSeconds()
                * BASE_RESEARCH_POINTS_PER_SECOND
                * researchDurationModifier(civilisation, technology, currentYear);
    }

    public static double estimatedSeconds(Civilisation civilisation,
                                          Technology technology,
                                          long currentYear) {
        if (civilisation == null || technology == null) return Double.POSITIVE_INFINITY;
        int researchers = Math.max(0, civilisation.getJobCount(VillagerJob.RESEARCHER));
        double speedMultiplier = 1.0 + researchers * RESEARCHER_SPEED_BONUS;
        return technology.getBaseResearchSeconds()
                * researchDurationModifier(civilisation, technology, currentYear)
                / speedMultiplier;
    }

    private static void grantBackwaterTechnologies(Civilisation civilisation, long currentYear) {
        List<Technology> ordered = DataManager.getTechnologies().values().stream()
                .filter(ResearchSystem::technologyExistsInCurrentModSet)
                .filter(technology -> technology.getBackwaterYear() != Long.MAX_VALUE)
                .filter(technology -> currentYear >= technology.getBackwaterYear())
                .sorted(Comparator.comparingLong(Technology::getBackwaterYear))
                .toList();
        // Repeat once over the sorted tree so prerequisite chains whose backwater
        // dates have all passed become available in the same strategy step.
        for (int pass = 0; pass < 3; pass++) {
            boolean changed = false;
            for (Technology technology : ordered) {
                if (civilisation.hasTechnology(technology.getId())) continue;
                if (!prerequisitesMet(civilisation, technology)) continue;
                completeTechnology(civilisation, technology, true);
                changed = true;
            }
            if (!changed) break;
        }
    }

    private static void tickActiveResearch(Civilisation civilisation, long currentYear) {
        String activeId = civilisation.getActiveTechnologyId();
        if (activeId == null || activeId.isBlank()) return;
        Technology technology = DataManager.getTechnologies().get(activeId);
        if (!canStart(civilisation, technology)) {
            civilisation.clearActiveTechnology();
            return;
        }

        int researchers = Math.max(0, civilisation.getJobCount(VillagerJob.RESEARCHER));
        double generated = BASE_RESEARCH_POINTS_PER_SECOND
                * (1.0 + researchers * RESEARCHER_SPEED_BONUS);

        // Focuses/events may award banked research points. Those are a bonus on top of
        // the guaranteed time-based rate, not the only source of research progression.
        double banked = civilisation.getResearchPoints();
        double bonus = banked <= 0.0 ? 0.0 : civilisation.consumeResearchPoints(banked);
        civilisation.addTechnologyProgress(generated + bonus);
        double needed = requiredResearchPoints(civilisation, technology, currentYear);
        if (civilisation.getActiveTechnologyProgress() + 1.0e-9 >= needed) {
            completeTechnology(civilisation, technology, false);
        }
    }

    public static double researchProgressFraction(Civilisation civilisation,
                                                  Technology technology,
                                                  long currentYear) {
        if (civilisation == null || technology == null) return 0.0;
        if (civilisation.hasTechnology(technology.getId())) return 1.0;
        if (!technology.getId().equals(civilisation.getActiveTechnologyId())) return 0.0;
        double needed = requiredResearchPoints(civilisation, technology, currentYear);
        if (!Double.isFinite(needed) || needed <= 0.0) return 0.0;
        return Math.max(0.0, Math.min(1.0, civilisation.getActiveTechnologyProgress() / needed));
    }

    public static double estimatedRemainingSeconds(Civilisation civilisation,
                                                    Technology technology,
                                                    long currentYear) {
        if (civilisation == null || technology == null) return Double.POSITIVE_INFINITY;
        double fraction = researchProgressFraction(civilisation, technology, currentYear);
        return Math.max(0.0, estimatedSeconds(civilisation, technology, currentYear) * (1.0 - fraction));
    }

    public static void completeTechnology(Civilisation civilisation, Technology technology, boolean backwater) {
        if (civilisation == null || technology == null) return;
        if (!civilisation.completeTechnology(technology.getId())) return;
        civilisation.addReligiousExtremism(technology.getReligiousExtremismDelta());
        civilisation.adjustPopulationReligiosity(technology.getPopulationReligiosityDelta());
        civilisation.addIdeologicalExtremism(technology.getIdeologicalExtremismDelta());
        civilisation.setStability(civilisation.getStability() + technology.getStabilityDelta());
        System.out.println("[GrandStrategy][Research] " + civilisation.getName()
                + (backwater ? " automatically caught up with " : " completed ")
                + technology.getName() + ".");
    }

    public static boolean factoryTypeAvailable(Civilisation civilisation, String factoryTypeId) {
        FactoryType type = DataManager.getFactoryTypes().get(factoryTypeId);
        if (civilisation == null || type == null) return false;
        if (type.isStarter()) return true;
        for (String technologyId : type.getRequiredTechnologyIds()) {
            if (!civilisation.hasTechnology(technologyId)) return false;
        }
        for (String itemId : type.getRequiredItemIds()) {
            if (!MinecraftItemRegistry.itemExists(itemId)) return false;
        }
        return true;
    }

    public static boolean recipeAvailable(Civilisation civilisation, FactoryRecipe recipe) {
        if (civilisation == null || recipe == null) return false;
        for (String technologyId : recipe.getRequiredTechnologyIds()) {
            if (!civilisation.hasTechnology(technologyId)) return false;
        }
        if (recipe.getOutputItemId() != null && !MinecraftItemRegistry.itemExists(recipe.getOutputItemId())) return false;
        for (String itemId : recipe.getRequiredItemIds()) {
            if (!MinecraftItemRegistry.itemExists(itemId)) return false;
        }
        for (String itemId : recipe.getIngredients().keySet()) {
            // A definition that refers to a missing mod item does not appear.
            if (!MinecraftItemRegistry.itemExists(itemId)) return false;
        }
        return true;
    }

    public static List<FactoryRecipe> recipesForFactoryTypes(Civilisation civilisation,
                                                             List<String> factoryTypeIds) {
        if (civilisation == null || factoryTypeIds == null) return List.of();
        return DataManager.getFactoryRecipes().values().stream()
                .filter(recipe -> recipeAvailable(civilisation, recipe))
                .filter(recipe -> recipe.getFactoryTypeIds().stream().anyMatch(factoryTypeIds::contains))
                .sorted(Comparator.comparing(FactoryRecipe::getName, Comparator.nullsLast(String::compareTo)))
                .toList();
    }

    public static WorkerToolTier maximumToolTier(Civilisation civilisation, VillagerJob job) {
        if (civilisation == null || job == null) return WorkerToolTier.HAND;
        WorkerToolTier maximum = WorkerToolTier.HAND;
        List<Technology> completed = new ArrayList<>();
        for (String id : civilisation.getCompletedTechnologyIds()) {
            Technology technology = DataManager.getTechnologies().get(id);
            if (technology != null) completed.add(technology);
        }
        for (Technology technology : completed) {
            for (Map.Entry<String, String> entry : technology.getUnlockToolTiers().entrySet()) {
                if (!("*".equals(entry.getKey()) || job.name().equalsIgnoreCase(entry.getKey()))) continue;
                try {
                    WorkerToolTier tier = WorkerToolTier.valueOf(entry.getValue().toUpperCase(Locale.ROOT));
                    if (tier.ordinal() > maximum.ordinal()) maximum = tier;
                } catch (IllegalArgumentException ignored) { }
            }
        }
        return maximum;
    }

    public static boolean canUseToolTier(Civilisation civilisation, VillagerJob job, WorkerToolTier tier) {
        if (tier == null || tier == WorkerToolTier.HAND) return true;
        return tier.ordinal() <= maximumToolTier(civilisation, job).ordinal();
    }

    public static boolean ideologyAvailable(Civilisation civilisation, Ideology ideology, long currentYear) {
        if (ideology == null || currentYear < ideology.getAvailableYear()) return false;
        if (civilisation != null) {
            for (String tech : ideology.getRequiredTechnologyIds()) {
                if (!civilisation.hasTechnology(tech)) return false;
            }
        }
        return true;
    }

    private static void resolveSnapIdeology(Civilisation civilisation, long currentYear) {
        String snap = civilisation.getSnapIdeologyId();
        if (snap == null || snap.isBlank() || snap.equals(civilisation.getIdeology())) return;
        Ideology ideology = DataManager.findIdeology(snap);
        if (ideologyAvailable(civilisation, ideology, currentYear)) {
            civilisation.setIdeology(snap);
            civilisation.shiftIdeologySupportToward(snap, 0.15);
            System.out.println("[GrandStrategy][Ideology] " + civilisation.getName()
                    + " adopted snap ideology " + ideology.getName() + ".");
        }
    }
}

