package com.asbestosstar.grandstrategy.common.gui;

import com.asbestosstar.grandstrategy.common.data.Civilisation;
import com.asbestosstar.grandstrategy.common.data.GrandStrategyEvent;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

/** Player decision screen for server-generated Grand Strategy events. */
public final class EventsScreen extends StrategyScreen {
	private String statusMessage = "";
	private int syncTicks;
	private String lastEventId;

	public EventsScreen(Screen parent) {
		super("Events", parent);
	}

	@Override
	protected void init() {
		beginIconLayout();
		addIconButton(UiIcon.BACK, "Back", 6, 6, button -> this.minecraft.setScreen(getParentScreen()));
		StrategyClientContext.requestSync();

		Civilisation civilisation = StrategyClientContext.currentPlayerCountry();
		lastEventId = civilisation == null ? null : civilisation.getPendingEventId();
		if (civilisation == null || !civilisation.hasPendingEvent())
			return;
		GrandStrategyEvent event = StrategyClientContext.event(civilisation.getPendingEventId());
		if (event == null)
			return;

		int y = 96;
		for (GrandStrategyEvent.EventOption option : event.getOptions()) {
			this.addRenderableWidget(Button.builder(Component.literal(option.getLabel()), button -> {
				boolean queued = StrategyClientContext.requestResolveEvent(event.getId(), option.getId());
				statusMessage = queued ? "Decision sent to server." : "Not connected to a Grand Strategy server.";
				if (queued)
					scheduleRefresh();
			}).bounds(24, y - 4, 220, 20).build());
			y += 44;
		}
	}

	@Override
	protected void renderCustom(GuiGraphicsExtractor graphics, int mouseX, int mouseY, float partialTick) {
		graphics.text(this.font, "Events & Decisions", 18, 40, TEXT, true);
		Civilisation civilisation = StrategyClientContext.currentPlayerCountry();
		if (civilisation == null) {
			graphics.text(this.font, "Create a country before receiving national events.", 18, 60, WARNING_TEXT, true);
			return;
		}

		if (!civilisation.hasPendingEvent()) {
			graphics.text(this.font, "No decision is currently waiting.", 18, 60, MUTED_TEXT, true);
			graphics.text(this.font,
					"Events are generated by the server and can alter resources, politics, diplomacy and long-term development.",
					18, 76, MUTED_TEXT, true);
			return;
		}

		GrandStrategyEvent event = StrategyClientContext.event(civilisation.getPendingEventId());
		if (event == null) {
			graphics.text(this.font, "The server is synchronising this event definition...", 18, 60, WARNING_TEXT,
					true);
			return;
		}

		graphics.text(this.font, event.getTitle(), 18, 60, WARNING_TEXT, true);
		graphics.text(this.font, event.getDescription(), 18, 76, TEXT, true);

		int y = 96;
		for (GrandStrategyEvent.EventOption option : event.getOptions()) {
			graphics.text(this.font, option.getDescription(), 254, y + 1, MUTED_TEXT, true);
			y += 44;
		}

		if (!statusMessage.isBlank()) {
			graphics.text(this.font, statusMessage, 18, this.height - 18, WARNING_TEXT, true);
		}
	}

	@Override
	public void tick() {
		super.tick();
		if (++syncTicks % 20 == 0)
			StrategyClientContext.requestSync();
		Civilisation civilisation = StrategyClientContext.currentPlayerCountry();
		String current = civilisation == null ? null : civilisation.getPendingEventId();
		if (!java.util.Objects.equals(current, lastEventId) && this.minecraft != null) {
			this.minecraft.setScreen(new EventsScreen(getParentScreen()));
		}
	}

	@Override
	protected StrategyScreen recreate() {
		return new EventsScreen(getParentScreen());
	}
}
